// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_83P9cHc_I8lXmiRyGW2F58MiHkRRqjw',
    appId: '1:502471827029:web:9f7dbc71df03d1b7a67edc',
    messagingSenderId: '502471827029',
    projectId: 'mant-suray',
    authDomain: 'mant-suray.firebaseapp.com',
    storageBucket: 'mant-suray.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkSlQB_xrL64y9rso5gQ6yiHOFBfjM6cU',
    appId: '1:502471827029:android:23860a45b202ecf9a67edc',
    messagingSenderId: '502471827029',
    projectId: 'mant-suray',
    storageBucket: 'mant-suray.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3Y5AMCm82MiTw-FzQe2SvdRkDD4YKbL0',
    appId: '1:502471827029:ios:d92a3eccf5f54e95a67edc',
    messagingSenderId: '502471827029',
    projectId: 'mant-suray',
    storageBucket: 'mant-suray.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_83P9cHc_I8lXmiRyGW2F58MiHkRRqjw',
    appId: '1:502471827029:web:28b9ccf96242e358a67edc',
    messagingSenderId: '502471827029',
    projectId: 'mant-suray',
    authDomain: 'mant-suray.firebaseapp.com',
    storageBucket: 'mant-suray.firebasestorage.app',
  );
}
